void 0===jQuery.migrateMute&&(jQuery.migrateMute=!0);
(function(a,b,g){function e(c){var h=b.console;d[c]||(d[c]=!0,a.migrateWarnings.push(c),h&&h.warn&&!a.migrateMute&&(h.warn("JQMIGRATE: "+c),a.migrateTrace&&h.trace&&h.trace()))}function r(c,h,t,w){if(Object.defineProperty)try{return Object.defineProperty(c,h,{configurable:!0,enumerable:!0,get:function(){return e(w),t},set:function(C){e(w);t=C}}),g}catch(C){}a._definePropertyBroken=!0;c[h]=t}var d={};a.migrateWarnings=[];!a.migrateMute&&b.console&&b.console.log&&b.console.log("JQMIGRATE: Logging is active");
a.migrateTrace===g&&(a.migrateTrace=!0);a.migrateReset=function(){d={};a.migrateWarnings.length=0};"BackCompat"===document.compatMode&&e("jQuery is not compatible with Quirks Mode");var q=a("<input/>",{size:1}).attr("size")&&a.attrFn,m=a.attr,n=a.attrHooks.value&&a.attrHooks.value.get||function(){return null},z=a.attrHooks.value&&a.attrHooks.value.set||function(){return g},p=/^(?:input|button)$/i,u=/^[238]$/,A=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,
y=/^(?:checked|selected)$/i;r(a,"attrFn",q||{},"jQuery.attrFn is deprecated");a.attr=function(c,h,t,w){var C=h.toLowerCase(),I=c&&c.nodeType;return w&&(4>m.length&&e("jQuery.fn.attr( props, pass ) is deprecated"),c&&!u.test(I)&&(q?h in q:a.isFunction(a.fn[h])))?a(c)[h](t):("type"===h&&t!==g&&p.test(c.nodeName)&&c.parentNode&&e("Can't change the 'type' of an input or button in IE 6/7/8"),!a.attrHooks[C]&&A.test(C)&&(a.attrHooks[C]={get:function(H,F){var J,L=a.prop(H,F);return!0===L||"boolean"!=typeof L&&
(J=H.getAttributeNode(F))&&!1!==J.nodeValue?F.toLowerCase():g},set:function(H,F,J){var L;return!1===F?a.removeAttr(H,J):(L=a.propFix[J]||J,L in H&&(H[L]=!0),H.setAttribute(J,J.toLowerCase())),J}},y.test(C)&&e("jQuery.fn.attr('"+C+"') may use property instead of attribute")),m.call(a,c,h,t))};a.attrHooks.value={get:function(c,h){var t=(c.nodeName||"").toLowerCase();return"button"===t?n.apply(this,arguments):("input"!==t&&"option"!==t&&e("jQuery.fn.attr('value') no longer gets properties"),h in c?c.value:
null)},set:function(c,h){var t=(c.nodeName||"").toLowerCase();return"button"===t?z.apply(this,arguments):("input"!==t&&"option"!==t&&e("jQuery.fn.attr('value', val) no longer sets properties"),c.value=h,g)}};var G,k,l=a.fn.init,v=a.parseJSON,E=/^([^<]*)(<[\w\W]+>)([^>]*)$/;a.fn.init=function(c,h,t){var w;return c&&"string"==typeof c&&!a.isPlainObject(h)&&(w=E.exec(a.trim(c)))&&w[0]&&("<"!==c.charAt(0)&&e("$(html) HTML strings must start with '<' character"),w[3]&&e("$(html) HTML text after last tag is ignored"),
"#"===w[0].charAt(0)&&(e("HTML string cannot start with a '#' character"),a.error("JQMIGRATE: Invalid selector string (XSS)")),h&&h.context&&(h=h.context),a.parseHTML)?l.call(this,a.parseHTML(w[2],h,!0),h,t):l.apply(this,arguments)};a.fn.init.prototype=a.fn;a.parseJSON=function(c){return c||null===c?v.apply(this,arguments):(e("jQuery.parseJSON requires a valid JSON string"),null)};a.uaMatch=function(c){c=c.toLowerCase();c=/(chrome)[ \/]([\w.]+)/.exec(c)||/(webkit)[ \/]([\w.]+)/.exec(c)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(c)||
/(msie) ([\w.]+)/.exec(c)||0>c.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(c)||[];return{browser:c[1]||"",version:c[2]||"0"}};a.browser||(G=a.uaMatch(navigator.userAgent),k={},G.browser&&(k[G.browser]=!0,k.version=G.version),k.chrome?k.webkit=!0:k.webkit&&(k.safari=!0),a.browser=k);r(a,"browser",a.browser,"jQuery.browser is deprecated");a.sub=function(){function c(t,w){return new c.fn.init(t,w)}a.extend(!0,c,this);c.superclass=this;c.fn=c.prototype=this();c.fn.constructor=c;c.sub=
this.sub;c.fn.init=function(t,w){return w&&w instanceof a&&!(w instanceof c)&&(w=c(w)),a.fn.init.call(this,t,w,h)};c.fn.init.prototype=c.fn;var h=c(document);return e("jQuery.sub() is deprecated"),c};a.ajaxSetup({converters:{"text json":a.parseJSON}});var D=a.fn.data;a.fn.data=function(c){var h,t,w=this[0];return!w||"events"!==c||1!==arguments.length||(h=a.data(w,c),t=a._data(w,c),h!==g&&h!==t||t===g)?D.apply(this,arguments):(e("Use of jQuery.fn.data('events') is deprecated"),t)};var P=/\/(java|ecma)script/i,
Q=a.fn.andSelf||a.fn.addBack;a.fn.andSelf=function(){return e("jQuery.fn.andSelf() replaced by jQuery.fn.addBack()"),Q.apply(this,arguments)};a.clean||(a.clean=function(c,h,t,w){h=h||document;h=!h.nodeType&&h[0]||h;h=h.ownerDocument||h;e("jQuery.clean() is deprecated");var C,I=[];if(a.merge(I,a.buildFragment(c,h).childNodes),t){var H=function(F){return!F.type||P.test(F.type)?w?w.push(F.parentNode?F.parentNode.removeChild(F):F):t.appendChild(F):g};for(c=0;null!=(h=I[c]);c++)a.nodeName(h,"script")&&
H(h)||(t.appendChild(h),h.getElementsByTagName!==g&&(C=a.grep(a.merge([],h.getElementsByTagName("script")),H),I.splice.apply(I,[c+1,0].concat(C)),c+=C.length))}return I});var S=a.event.add,T=a.event.remove,R=a.event.trigger,f=a.fn.toggle,B=a.fn.live,K=a.fn.die,N=RegExp("\\b(?:ajaxStart|ajaxStop|ajaxSend|ajaxComplete|ajaxError|ajaxSuccess)\\b"),O=/(?:^|\s)hover(\.\S+|)\b/,M=function(c){return"string"!=typeof c||a.event.special.hover?c:(O.test(c)&&e("'hover' pseudo-event is deprecated, use 'mouseenter mouseleave'"),
c&&c.replace(O,"mouseenter$1 mouseleave$1"))};a.event.props&&"attrChange"!==a.event.props[0]&&a.event.props.unshift("attrChange","attrName","relatedNode","srcElement");a.event.dispatch&&r(a.event,"handle",a.event.dispatch,"jQuery.event.handle is undocumented and deprecated");a.event.add=function(c,h,t,w,C){c!==document&&N.test(h)&&e("AJAX events should be attached to document: "+h);S.call(this,c,M(h||""),t,w,C)};a.event.remove=function(c,h,t,w,C){T.call(this,c,M(h)||"",t,w,C)};a.fn.error=function(){var c=
Array.prototype.slice.call(arguments,0);return e("jQuery.fn.error() is deprecated"),c.splice(0,0,"error"),arguments.length?this.bind.apply(this,c):(this.triggerHandler.apply(this,c),this)};a.fn.toggle=function(c,h){if(!a.isFunction(c)||!a.isFunction(h))return f.apply(this,arguments);e("jQuery.fn.toggle(handler, handler...) is deprecated");var t=arguments,w=c.guid||a.guid++,C=0,I=function(H){var F=(a._data(this,"lastToggle"+c.guid)||0)%C;return a._data(this,"lastToggle"+c.guid,F+1),H.preventDefault(),
t[F].apply(this,arguments)||!1};for(I.guid=w;t.length>C;)t[C++].guid=w;return this.click(I)};a.fn.live=function(c,h,t){return e("jQuery.fn.live() is deprecated"),B?B.apply(this,arguments):(a(this.context).on(c,this.selector,h,t),this)};a.fn.die=function(c,h){return e("jQuery.fn.die() is deprecated"),K?K.apply(this,arguments):(a(this.context).off(c,this.selector||"**",h),this)};a.event.trigger=function(c,h,t,w){return t||N.test(c)||e("Global events are undocumented and deprecated"),R.call(this,c,h,
t||document,w)};a.each("ajaxStart ajaxStop ajaxSend ajaxComplete ajaxError ajaxSuccess".split(" "),function(c,h){a.event.special[h]={setup:function(){var t=this;return t!==document&&(a.event.add(document,h+"."+a.guid,function(){a.event.trigger(h,null,t,!0)}),a._data(this,h,a.guid++)),!1},teardown:function(){return this!==document&&a.event.remove(document,h+"."+a._data(this,h)),!1}}})})(jQuery,window);
!function(a,b){var g=function(){var e=function(){var k=/^(?![\w\W]*Windows Phone)[\w\W]*(iPhone|iPad|iPod)/i.test(navigator.userAgent);return k&&a("html").css("cursor","pointer").on("click",a.noop),k}(),r=function(){var k=document.documentElement.style;return"behavior"in k&&"fill"in k&&/iemobile/i.test(navigator.userAgent)}(),d=!!b.PointerEvent,q=function(k,l,v){var E="sf-js-enabled";l.cssArrows&&(E+=" sf-arrows");k[v?"addClass":"removeClass"](E)},m=function(k,l){return k.find("li."+l.pathClass).slice(0,
l.pathLevels).addClass(l.hoverClass+" sf-breadcrumb").filter(function(){return a(this).children(l.popUpSelector).hide().show().length}).removeClass(l.pathClass)},n=function(k,l){var v=l?"addClass":"removeClass";k.children("a")[v]("sf-with-ul")},z=function(k){var l=k.css("ms-touch-action"),v=k.css("touch-action");v="pan-y"===(v||l)?"auto":"pan-y";k.css({"ms-touch-action":v,"touch-action":v})},p=function(k){return k.closest(".sf-js-enabled").data("sfOptions")},u=function(){var k=a(this),l=p(k);clearTimeout(l.sfTimer);
k.siblings().superfish("hide").end().superfish("show")},A=function(k){k.retainPath=-1<a.inArray(this[0],k.$path);this.superfish("hide");this.parents("."+k.hoverClass).length||(k.onIdle.call(this.closest(".sf-js-enabled")),k.$path.length&&a.proxy(u,k.$path)())},y=function(){var k=a(this),l=p(k);e?a.proxy(A,k,l)():(clearTimeout(l.sfTimer),l.sfTimer=setTimeout(a.proxy(A,k,l),l.delay))},G=function(k){var l=a(this),v=p(l),E=l.siblings(k.data.popUpSelector);return!1===v.onHandleTouch.call(E)?this:void(0<
E.length&&E.is(":hidden")&&(l.one("click.superfish",!1),"MSPointerDown"===k.type||"pointerdown"===k.type?l.trigger("focus"):a.proxy(u,l.parent("li"))()))};return{hide:function(k){if(this.length){var l=p(this);if(!l)return this;var v=!0===l.retainPath?l.$path:"";v=this.find("li."+l.hoverClass).add(this).not(v).removeClass(l.hoverClass).children(l.popUpSelector);var E=l.speedOut;if(k&&(v.show(),E=0),l.retainPath=!1,!1===l.onBeforeHide.call(v))return this;v.stop(!0,!0).animate(l.animationOut,E,function(){var D=
a(this);l.onHide.call(D)})}return this},show:function(){var k=p(this);if(!k)return this;var l=this.addClass(k.hoverClass).children(k.popUpSelector);return!1===k.onBeforeShow.call(l)?this:(l.stop(!0,!0).animate(k.animation,k.speed,function(){k.onShow.call(l)}),this)},destroy:function(){return this.each(function(){var k,l=a(this),v=l.data("sfOptions");return v?(k=l.find(v.popUpSelector).parent("li"),clearTimeout(v.sfTimer),q(l,v),n(k),z(l),l.off(".superfish").off(".hoverIntent"),k.children(v.popUpSelector).attr("style",
function(E,D){return D.replace(/display[^;]+;?/g,"")}),v.$path.removeClass(v.hoverClass+" sf-breadcrumb").addClass(v.pathClass),l.find("."+v.hoverClass).removeClass(v.hoverClass),v.onDestroy.call(l),void l.removeData("sfOptions")):!1})},init:function(k){return this.each(function(){var l=a(this);if(l.data("sfOptions"))return!1;var v=a.extend({},a.fn.superfish.defaults,k),E=l.find(v.popUpSelector).parent("li");v.$path=m(l,v);l.data("sfOptions",v);q(l,v,!0);n(E,!0);z(l);var D="li:has("+v.popUpSelector+
")";a.fn.hoverIntent&&!v.disableHI?l.hoverIntent(u,y,D):l.on("mouseenter.superfish",D,u).on("mouseleave.superfish",D,y);D="MSPointerDown.superfish";d&&(D="pointerdown.superfish");e||(D+=" touchend.superfish");r&&(D+=" mousedown.superfish");l.on("focusin.superfish","li",u).on("focusout.superfish","li",y).on(D,"a",v,G);E.not(".sf-breadcrumb").superfish("hide",!0);v.onInit.call(this)})}}}();a.fn.superfish=function(e,r){return g[e]?g[e].apply(this,Array.prototype.slice.call(arguments,1)):"object"!=typeof e&&
e?a.error("Method "+e+" does not exist on jQuery.fn.superfish"):g.init.apply(this,arguments)};a.fn.superfish.defaults={popUpSelector:"ul,.sf-mega",hoverClass:"sfHover",pathClass:"overrideThisToUse",pathLevels:1,delay:800,animation:{opacity:"show"},animationOut:{opacity:"hide"},speed:"normal",speedOut:"fast",cssArrows:!0,disableHI:!1,onInit:a.noop,onBeforeShow:a.noop,onShow:a.noop,onBeforeHide:a.noop,onHide:a.noop,onIdle:a.noop,onDestroy:a.noop,onHandleTouch:a.noop}}(jQuery,window);
(function(a,b,g){function e(d,q){this.element=d;this.settings=a.extend({},r,q);this._defaults=r;this._name="slicknav";this.init()}var r={label:"MENU",duplicate:!0,duration:200,easingOpen:"swing",easingClose:"swing",closedSymbol:"&#9658;",openedSymbol:"&#9660;",prependTo:"body",parentTag:"a",closeOnClick:!1,allowParentLinks:!1,nestedParentLinks:!0,showChildren:!1,removeIds:!1,removeClasses:!1,brand:"",init:function(){},beforeOpen:function(){},beforeClose:function(){},afterOpen:function(){},afterClose:function(){}};
e.prototype.init=function(){var d=this,q=a(this.element),m=this.settings;m.duplicate?(d.mobileNav=q.clone(),d.mobileNav.removeAttr("id"),d.mobileNav.find("*").each(function(p,u){a(u).removeAttr("id")})):(d.mobileNav=q,d.mobileNav.removeAttr("id"),d.mobileNav.find("*").each(function(p,u){a(u).removeAttr("id")}));m.removeClasses&&(d.mobileNav.removeAttr("class"),d.mobileNav.find("*").each(function(p,u){a(u).removeAttr("class")}));q="slicknav_icon";""===m.label&&(q+=" slicknav_no-text");"a"==m.parentTag&&
(m.parentTag='a href="#"');d.mobileNav.attr("class","slicknav_nav");var n=a('<div class="slicknav_menu"></div>');if(""!==m.brand){var z=a('<div class="slicknav_brand">'+m.brand+"</div>");a(n).append(z)}d.btn=a(["<"+m.parentTag+' aria-haspopup="true" tabindex="0" class="slicknav_btn slicknav_collapsed">','<span class="slicknav_menutxt">'+m.label+"</span>",'<span class="'+q+'">','<span class="slicknav_icon-bar"></span><span class="slicknav_icon-bar"></span><span class="slicknav_icon-bar"></span></span>',
"</"+m.parentTag+">"].join(""));a(n).append(d.btn);a(m.prependTo).prepend(n);n.append(d.mobileNav);q=d.mobileNav.find("li");a(q).each(function(){var p=a(this),u={};u.children=p.children("ul").attr("role","menu");p.data("menu",u);if(0<u.children.length){u=p.contents();var A=!1,y=[];a(u).each(function(){if(a(this).is("ul"))return!1;y.push(this);a(this).is("a")&&(A=!0)});u=a("<"+m.parentTag+' role="menuitem" aria-haspopup="true" tabindex="-1" class="slicknav_item"/>');m.allowParentLinks&&!m.nestedParentLinks&&
A?a(y).wrapAll('<span class="slicknav_parent-link slicknav_row"/>').parent():a(y).wrapAll(u).parent().addClass("slicknav_row");m.showChildren?p.addClass("slicknav_open"):p.addClass("slicknav_collapsed");p.addClass("slicknav_parent");var G=a('<span class="slicknav_arrow">'+(m.showChildren?m.openedSymbol:m.closedSymbol)+"</span>");m.allowParentLinks&&!m.nestedParentLinks&&A&&(G=G.wrap(u).parent());a(y).last().after(G)}else 0===p.children().length&&p.addClass("slicknav_txtnode");p.children("a").attr("role",
"menuitem").click(function(k){m.closeOnClick&&!a(k.target).parent().closest("li").hasClass("slicknav_parent")&&a(d.btn).click()});m.closeOnClick&&m.allowParentLinks&&(p.children("a").children("a").click(function(k){a(d.btn).click()}),p.find(".slicknav_parent-link a:not(.slicknav_item)").click(function(k){a(d.btn).click()}))});a(q).each(function(){var p=a(this).data("menu");m.showChildren||d._visibilityToggle(p.children,null,!1,null,!0)});d._visibilityToggle(d.mobileNav,null,!1,"init",!0);d.mobileNav.attr("role",
"menu");a(b).mousedown(function(){d._outlines(!1)});a(b).keyup(function(){d._outlines(!0)});a(d.btn).click(function(p){p.preventDefault();d._menuToggle()});d.mobileNav.on("click",".slicknav_item",function(p){p.preventDefault();d._itemClick(a(this))});a(d.btn).keydown(function(p){13==(p||event).keyCode&&(p.preventDefault(),d._menuToggle())});d.mobileNav.on("keydown",".slicknav_item",function(p){13==(p||event).keyCode&&(p.preventDefault(),d._itemClick(a(p.target)))});m.allowParentLinks&&m.nestedParentLinks&&
a(".slicknav_item a").click(function(p){p.stopImmediatePropagation()})};e.prototype._menuToggle=function(d){d=this.btn;var q=this.mobileNav;d.hasClass("slicknav_collapsed")?(d.removeClass("slicknav_collapsed"),d.addClass("slicknav_open")):(d.removeClass("slicknav_open"),d.addClass("slicknav_collapsed"));d.addClass("slicknav_animating");this._visibilityToggle(q,d.parent(),!0,d)};e.prototype._itemClick=function(d){var q=this,m=q.settings,n=d.data("menu");n||(n={},n.arrow=d.children(".slicknav_arrow"),
n.ul=d.next("ul"),n.parent=d.parent(),n.parent.hasClass("slicknav_parent-link")&&(n.parent=d.parent().parent(),n.ul=d.parent().next("ul")),d.data("menu",n));n.parent.hasClass("slicknav_collapsed")?(n.parent.siblings(".slicknav_open").each(function(){var z=a(this),p=z.children("a"),u=p.next("ul");p.children(".slicknav_arrow").html(m.closedSymbol);z.addClass("slicknav_collapsed").addClass("slicknav_animating").removeClass("slicknav_open");q._visibilityToggle(u,z,!0,p)}),n.arrow.html(m.openedSymbol),
n.parent.removeClass("slicknav_collapsed"),n.parent.addClass("slicknav_open")):(n.arrow.html(m.closedSymbol),n.parent.addClass("slicknav_collapsed"),n.parent.removeClass("slicknav_open"));n.parent.addClass("slicknav_animating");q._visibilityToggle(n.ul,n.parent,!0,d)};e.prototype._visibilityToggle=function(d,q,m,n,z){var p=this,u=p.settings,A=p._getActionItems(d),y=0;m&&(y=u.duration);d.hasClass("slicknav_hidden")?(d.removeClass("slicknav_hidden"),z||u.beforeOpen(n),d.slideDown(y,u.easingOpen,function(){a(n).removeClass("slicknav_animating");
a(q).removeClass("slicknav_animating");z||u.afterOpen(n)}),d.attr("aria-hidden","false"),A.attr("tabindex","0"),p._setVisAttr(d,!1)):(d.addClass("slicknav_hidden"),z||u.beforeClose(n),d.slideUp(y,this.settings.easingClose,function(){d.attr("aria-hidden","true");A.attr("tabindex","-1");p._setVisAttr(d,!0);d.hide();a(n).removeClass("slicknav_animating");a(q).removeClass("slicknav_animating");z?"init"==n&&u.init():u.afterClose(n)}))};e.prototype._setVisAttr=function(d,q){var m=this,n=d.children("li").children("ul").not(".slicknav_hidden");
q?n.each(function(){var z=a(this);z.attr("aria-hidden","true");m._getActionItems(z).attr("tabindex","-1");m._setVisAttr(z,q)}):n.each(function(){var z=a(this);z.attr("aria-hidden","false");m._getActionItems(z).attr("tabindex","0");m._setVisAttr(z,q)})};e.prototype._getActionItems=function(d){var q=d.data("menu");if(!q){q={};var m=d.children("li"),n=m.find("a");q.links=n.add(m.find(".slicknav_item"));d.data("menu",q)}return q.links};e.prototype._outlines=function(d){d?a(".slicknav_item, .slicknav_btn").css("outline",
""):a(".slicknav_item, .slicknav_btn").css("outline","none")};e.prototype.toggle=function(){this._menuToggle()};e.prototype.open=function(){this.btn.hasClass("slicknav_collapsed")&&this._menuToggle()};e.prototype.close=function(){this.btn.hasClass("slicknav_open")&&this._menuToggle()};a.fn.slicknav=function(d){var q=arguments;if(void 0===d||"object"===typeof d)return this.each(function(){a.data(this,"plugin_slicknav")||a.data(this,"plugin_slicknav",new e(this,d))});if("string"===typeof d&&"_"!==d[0]&&
"init"!==d){var m;this.each(function(){var n=a.data(this,"plugin_slicknav");n instanceof e&&"function"===typeof n[d]&&(m=n[d].apply(n,Array.prototype.slice.call(q,1)))});return void 0!==m?m:this}}})(jQuery,document,window);
(function(a){a.fn.hoverIntent=function(b,g,e){var r={interval:100,sensitivity:7,timeout:0};r="object"===typeof b?a.extend(r,b):a.isFunction(g)?a.extend(r,{over:b,out:g,selector:e}):a.extend(r,{over:b,out:b,selector:g});var d,q,m,n,z=function(u){d=u.pageX;q=u.pageY},p=function(u,A){A.hoverIntent_t=clearTimeout(A.hoverIntent_t);if(Math.abs(m-d)+Math.abs(n-q)<r.sensitivity)return a(A).off("mousemove.hoverIntent",z),A.hoverIntent_s=1,r.over.apply(A,[u]);m=d;n=q;A.hoverIntent_t=setTimeout(function(){p(u,
A)},r.interval)};b=function(u){var A=jQuery.extend({},u),y=this;y.hoverIntent_t&&(y.hoverIntent_t=clearTimeout(y.hoverIntent_t));"mouseenter"==u.type?(m=A.pageX,n=A.pageY,a(y).on("mousemove.hoverIntent",z),1!=y.hoverIntent_s&&(y.hoverIntent_t=setTimeout(function(){p(A,y)},r.interval))):(a(y).off("mousemove.hoverIntent",z),1==y.hoverIntent_s&&(y.hoverIntent_t=setTimeout(function(){y.hoverIntent_t=clearTimeout(y.hoverIntent_t);y.hoverIntent_s=0;r.out.apply(y,[A])},r.timeout)))};return this.on({"mouseenter.hoverIntent":b,
"mouseleave.hoverIntent":b},r.selector)}})(jQuery);
(function(){var a;var b=jQuery;var g=b('<div id="jquery-fullsizable"><div id="fullsized_image_holder"></div></div>');var e=[];var r=0;var d=a=null;var q=function(){var f;return f=e[r],null==f.ratio&&(f.ratio=(f.naturalHeight/f.naturalWidth).toFixed(2)),b(window).height()/f.ratio>b(window).width()?(b(f).width(b(window).width()),b(f).height(b(window).width()*f.ratio),b(f).css("margin-top",(b(window).height()-b(f).height())/2)):(b(f).height(b(window).height()),b(f).width(b(window).height()/f.ratio),
b(f).css("margin-top",0))};var m=function(f){return 27===f.keyCode&&y(),37===f.keyCode&&n(!0),39===f.keyCode?z(!0):void 0};var n=function(f){return null==f&&(f=!1),0<r?p(e[r-1],-1,f):a.loop?p(e[e.length-1],-1,f):void 0};var z=function(f){return null==f&&(f=!1),r<e.length-1?p(e[r+1],1,f):a.loop?p(e[0],1,f):void 0};var p=function(f,B,K){return null==B&&(B=1),null==K&&(K=!1),r=f.index,b("#fullsized_image_holder").hide(),b("#fullsized_image_holder").html(f),a.navigation&&(!0===K?E():Q()),null!=f.loaded?
(b("#jquery-fullsizable").removeClass("fullsized_spinner"),q(),b("#fullsized_image_holder").fadeIn("fast"),u(B)):(b("#jquery-fullsizable").addClass("fullsized_spinner"),f.onload=function(){return q(),b("#fullsized_image_holder").fadeIn("slow",function(){return b("#jquery-fullsizable").removeClass("fullsized_spinner")}),this.loaded=!0,u(B)},f.src=f.buffer_src)};var u=function(f){if(1===f&&r<e.length-1)f=e[r+1];else{if(-1!==f&&r!==e.length-1||!(0<r))return;f=e[r-1]}return f.onload=function(){return this.loaded=
!0},""===f.src?f.src=f.buffer_src:void 0};var A=function(f,B){return b("body").append(g),b(window).bind("resize",q),p(f),b("#jquery-fullsizable").hide().fadeIn(function(){return null!=a.detach_id&&(d=b(window).scrollTop(),b("#"+a.detach_id).css("display","none"),q()),l(),b(document).trigger("fullsizable:opened",B)})};var y=function(){return null!=a.detach_id&&(b("#"+a.detach_id).css("display","block"),b(window).scrollTop(d)),b("#jquery-fullsizable").fadeOut(function(){return g.remove()}),T(),b("#jquery-fullsizable").removeClass("fullsized_spinner"),
v(),b(window).unbind("resize",q)};var G=function(){return e.length=0,b(a.selector).each(function(){var f;return f=new Image,f.buffer_src=b(this).attr("href"),f.index=e.length,e.push(f),a.openOnClick?b(this).click(function(B){return B.preventDefault(),a.reloadOnOpen&&G(),A(f,this)}):void 0})};var k=function(){switch(a.navigation&&(g.append('<a id="fullsized_go_prev" href="#prev"></a><a id="fullsized_go_next" href="#next"></a>'),b(document).on("click","#fullsized_go_prev",function(f){return f.preventDefault(),
f.stopPropagation(),n()}),b(document).on("click","#fullsized_go_next",function(f){return f.preventDefault(),f.stopPropagation(),z()})),a.closeButton&&(g.append('<a id="fullsized_close" href="#close"></a>'),b(document).on("click","#fullsized_close",function(f){return f.preventDefault(),f.stopPropagation(),y()})),a.fullscreenButton&&S()&&(g.append('<a id="fullsized_fullscreen" href="#fullscreen"></a>'),b(document).on("click","#fullsized_fullscreen",function(f){return f.preventDefault(),f.stopPropagation(),
R()})),a.clickBehaviour){case "close":return b(document).on("click","#jquery-fullsizable",y);case "next":return b(document).on("click","#jquery-fullsizable",function(){return z(!0)});default:return b(document).on("click","#jquery-fullsizable",a.clickBehaviour)}};var l=function(){return b(document).bind("keydown",m),b(document).bind("fullsizable:next",function(){return z(!0)}),b(document).bind("fullsizable:prev",function(){return n(!0)}),b(document).bind("fullsizable:close",y)};var v=function(){return b(document).unbind("keydown",
m),b(document).unbind("fullsizable:next"),b(document).unbind("fullsizable:prev"),b(document).unbind("fullsizable:close")};var E=function(){var f;return f=g.find("a"),!0===f.is(":visible")?(f.toggle(!1),g.bind("mousemove",P)):void 0};var D=null;var P=function(f){var B;return null===D&&(D=[f.clientX,f.clientY]),B=Math.round(Math.sqrt(Math.pow(D[1]-f.clientY,2)+Math.pow(D[0]-f.clientX,2))),10<=B?(g.unbind("mousemove",P),D=null,Q()):void 0};var Q=function(){return b("#fullsized_close, #fullsized_fullscreen").toggle(!0),
a.loop?(b("#fullsized_go_prev").show(),b("#fullsized_go_next").show()):(b("#fullsized_go_prev").toggle(0!==r),b("#fullsized_go_next").toggle(r!==e.length-1))};b.fn.fullsizable=function(f){return a=b.extend({selector:this.selector,detach_id:null,navigation:!0,closeButton:!0,fullscreenButton:!0,openOnClick:!0,clickBehaviour:"close",preload:!0,reloadOnOpen:!1,loop:!1},f||{}),k(),a.preload&&G(),b(document).bind("fullsizable:reload",G),b(document).bind("fullsizable:open",function(B,K){var N;a.reloadOnOpen&&
G();var O=[];var M=0;for(N=e.length;N>M;M++){var c=e[M];O.push(c.buffer_src===b(K).attr("href")?A(c,K):void 0)}return O}),this};var S=function(){var f;return f=g.get(0),f.requestFullScreen||f.webkitRequestFullScreen||f.mozRequestFullScreen?!0:!1};var T=function(){return R(!0)};var R=function(f){var B;return B=g.get(0),B.requestFullScreen?document.fullScreen||f?document.exitFullScreen():B.requestFullScreen():B.webkitRequestFullScreen?document.webkitIsFullScreen||f?document.webkitCancelFullScreen():
B.webkitRequestFullScreen():B.mozRequestFullScreen?document.mozFullScreen||f?document.mozCancelFullScreen():B.mozRequestFullScreen():void 0}}).call(this);
jQuery(document).ready(function(a){a(".alert-msg .close").click(function(){a(this).parent().animate({opacity:"0"},400).slideUp(400);return!1});a(".accordion-title").click(function(){a(".accordion-title").removeClass("active");a(".accordion-content").slideUp("normal");1==a(this).next().is(":hidden")&&(a(this).addClass("active"),a(this).next().slideDown("normal"))});a(".accordion-content").hide();a(".toggle-title").click(function(){a(this).toggleClass("active").next().slideToggle("fast");return!1});
a(".tab-wrapper").tabs({event:"click"});a.fn.flexVerticalCenter=function(b){return this.each(function(){var g=a(this),e=b||"margin-top",r=function(){g.css(e,(g.parent().height()-g.height())/2)};r();a(window).resize(r)})};a(".viewit").flexVerticalCenter()});var AkoDpl;
function gateKeeper(a,b){AkoDpl=b;Gk=a;var g=readCookie(b),e=readCookie("BAR");g||e?(g=chkQ(Gk),window.location=g):"40"==Gk&&"UPL"==b?readCookie("ORU")?window.location="Upl.html":readCookie("ORUs")?window.location="Upl.html":readCookie("PB")?window.location="Upl.html":readCookie("TPR")?window.location="Upl.html":readCookie("PUB")?window.location="Upl.html":readCookie("UP")?window.location="Upl.html":readCookie("UOP")?window.location="Upl.html":readCookie("OPB")?window.location="Upl.html":readCookie("DPL")?
window.location="Upl.html":readCookie("BAR")?window.location="Upl.html":(alert("Za pristup ovom sadr\u017eaju, potrebno je u\u010diniti Prijavu korisnika u donjem djelu ove strane !!"),scrollToAnchor("anchPrijava")):(alert("Za pristup ovom sadr\u017eaju, potrebno je u\u010diniti Prijavu korisnika u donjem djelu ove strane !!"),scrollToAnchor("anchPrijava"))}
function chkQ(a){""!==a?(loc="docs/"+a+".pdf","40"==a?loc="Upl.html":"30"==a?loc="Dow.html":"10"==a?loc="Dpl.html":"50"==a&&(loc="https://www.bimco.org/Authentication/Members-Only?returnUrl=%2fcontracts-and-clauses%2fbimco-contracts")):loc="";return loc}
function submitentry(){username=document.prijava.korisnik.value.toLowerCase();password=document.prijava.zaporka.value.toLowerCase();usercode=passcode=1;for(i=0;i<password.length;i++)passcode*=password.charCodeAt(i);for(x=0;x<username.length;x++)usercode*=username.charCodeAt(x);if("undefined"==typeof Gk)1480518==usercode&&41849172==passcode?chkOK("ORU"):1480518==usercode&&35415930==passcode?chkOK("ORUs"):10976==usercode&&30293760==passcode?chkOK("PB"):1481088==usercode&&27315600==passcode?chkOK("TPR"):
1284192==usercode&&38524640==passcode?chkOK("PUB"):13104==usercode&&32815800==passcode?chkOK("UP"):1454544==usercode&&28408632==passcode?chkOK("UOP"):1218336==usercode&&33146355==passcode?chkOK("OPB"):1266035==usercode&&31427463==passcode?chkOK("SEM"):1209600==usercode&&28274400==passcode?chkOK("DPL"):1415232==usercode&&35224860==passcode?chkOK("UPL"):1320900==usercode&&31416E3==passcode?chkOK("DOW"):92236816==usercode&&92236816==passcode?chkOK("BAR"):(document.getElementById("ok").setAttribute("class",
"osx-err-hiden"),document.getElementById("er").setAttribute("class","osx-err-active"));else{if(0==Gk.length)return"";var a=chkQ(Gk);var b=Gk,g=b.indexOf("-");b=b.slice(g+1);(1480518==usercode&&41849172==passcode||92236816==usercode&&92236816==passcode)&&"Oru"==b?(scrollToAnchor("anchVrh"),goForit(a,"ORU")):(1480518==usercode&&35415930==passcode||92236816==usercode&&92236816==passcode)&&"Orus"==b?(scrollToAnchor("anchVrh"),goForit(a,"ORUs")):(10976==usercode&&30293760==passcode||92236816==usercode&&
92236816==passcode)&&"Pb"==b?(scrollToAnchor("anchVrh"),goForit(a,"PB")):(1481088==usercode&&27315600==passcode||92236816==usercode&&92236816==passcode)&&"Tpr"==b?(scrollToAnchor("anchVrh"),goForit(a,"TPR")):(1284192==usercode&&38524640==passcode||92236816==usercode&&92236816==passcode)&&"Pub"==b?(scrollToAnchor("anchVrh"),goForit(a,"PUB")):(13104==usercode&&32815800==passcode||92236816==usercode&&92236816==passcode)&&"Up"==b?(scrollToAnchor("anchVrh"),goForit(a,"UP")):(1454544==usercode&&28408632==
passcode||92236816==usercode&&92236816==passcode)&&"Uop"==b?(scrollToAnchor("anchVrh"),goForit(a,"UOP")):(1218336==usercode&&33146355==passcode||92236816==usercode&&92236816==passcode)&&"Opb"==b?(scrollToAnchor("anchVrh"),goForit(a,"OPB")):(1266035==usercode&&31427463==passcode||92236816==usercode&&92236816==passcode)&&"20"==b?(scrollToAnchor("anchVrh"),goForit(a,"SEM")):(1209600==usercode&&28274400==passcode||92236816==usercode&&92236816==passcode)&&"DPL"==AkoDpl?(scrollToAnchor("anchVrh"),goForit(a,
"DPL")):(1415232==usercode&&35224860==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?goForit(a,"UPL"):(1320900==usercode&&31416E3==passcode||92236816==usercode&&92236816==passcode)&&"30"==b?goForit(a,"DOW"):(13104==usercode&&32815800==passcode||92236816==usercode&&92236816==passcode)&&"50"==b?(scrollToAnchor("anchVrh"),goForit(a,"UP")):(1480518==usercode&&41849172==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","ORU")):(1480518==
usercode&&35415930==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","ORUs")):(10976==usercode&&30293760==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","PB")):(1481088==usercode&&27315600==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","TPR")):(1284192==usercode&&38524640==passcode||92236816==usercode&&92236816==passcode)&&"40"==
b?(scrollToAnchor("anchVrh"),goForit("Upl.html","PUB")):(13104==usercode&&32815800==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","UP")):(1454544==usercode&&28408632==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","UOP")):(1218336==usercode&&33146355==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","OPB")):(1266035==usercode&&
31427463==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","SEM")):(1209600==usercode&&28274400==passcode||92236816==usercode&&92236816==passcode)&&"40"==b?(scrollToAnchor("anchVrh"),goForit("Upl.html","DPL")):(document.getElementById("ok").setAttribute("class","osx-err-hiden"),document.getElementById("er").setAttribute("class","osx-err-active"))}}
function goForit(a,b){92236816==usercode?createCookie("BAR",1,300):"DOW"==b||"UPL"==b?createCookie(b,1,1):createCookie(b,1,25);fetch(a)}function fetch(a){window.location=a}function readCookie(a){a+="=";for(var b=document.cookie.split(";"),g=0;g<b.length;g++){for(var e=b[g];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return null}
function createCookie(a,b,g){if(g){var e=new Date;e.setTime(e.getTime()+864E5*g);g="; expires="+e.toGMTString()}else g="";document.cookie=a+"="+b+g+"; path=/"}function scrollToAnchor(a){a=$("a[name='"+a+"']");$("html,body").animate({scrollTop:a.offset().top},"slow")}function scrollToAnchorSlike(a){599>$(window).width()&&(a=$("a[name='"+a+"']"),$("html,body").animate({scrollTop:a.offset().top},"slow"))}
function clickEr(){document.getElementById("er").setAttribute("class","osx-err-hiden");document.getElementById("ok").setAttribute("class","osx-err-hiden")}function chkOK(a){"BAR"==a?createCookie(a,1,300):createCookie(a,1,25);document.getElementById("ok").setAttribute("class","osx-err-active-2")}
document.addEventListener("DOMContentLoaded",function(){var a=$(".slickm"),b=$(".row3").eq(0),g=b.attr("style")||"",e,r;$(window).resize(function(){e=a.outerHeight();r=$(".row1").outerHeight()}).resize().scroll(function(){$(this).scrollTop()>r?(a.addClass("page-head-scrolled"),b.css("margin-top",e)):(a.removeClass("page-head-scrolled"),b.attr("style",g))}).on("load",function(){$(this).scroll()})});
(function(a){a(document).ready(function(){a("#topnav").superfish({delay:200,speed:"fast",speedOut:"fast",cssArrows:!1})})})(jQuery);unhidediv=function(a,b,g,e,r,d,q){$(a).removeClass("downdiv");$(b).addClass("downdiv");$(g).addClass("downdiv");$(e).addClass("downdiv");$(r).addClass("downdiv");$(d).addClass("downdiv");$(q).addClass("downdiv")};
function slideSwitch(){var a=$("#slideshow IMG.active");0==a.length&&(a=$("#slideshow IMG:last"));var b=a.next().length?a.next():$("#slideshow IMG:first");a.addClass("last-active");b.css({opacity:0}).addClass("active").animate({opacity:1},1E3,function(){a.removeClass("active last-active")})}function slick(){$("#topnav").slicknav({duration:500,prependTo:".slickm",closeOnClick:!0,brand:"dr.sc.Mirano Hess, PFRI",closedSymbol:"&#9658;",openedSymbol:"&#9660;"})}
$("html").on("click",function(a){0===$(".slicknav_menu").has(a.target).length&&$("#topnav").slicknav("close")});function fullsiz(){$("#fscontain a").fullsizable({detach_id:"fscontain",navigation:!0,closeButton:!0,clickBehaviour:"close",loop:!0})}
$(document).ready(function(){function a(){var g=$(window).innerHeight()-$(".row1").height()-$(".row2").height()-$(".row4").height()-$(".row7").height()-12;$(".row3").css({width:"auto","min-height":g+"px"})}a();var b=function(g,e,r){var d;return function(){var q=this,m=arguments,n=r&&!d;clearTimeout(d);d=setTimeout(function(){d=null;r||g.apply(q,m)},e);n&&g.apply(q,m)}}(function(){a()},250);window.addEventListener("resize",b)});
function addListener(a,b,g){b.addEventListener?b.addEventListener(a,g,!1):b.attachEvent("on"+a,g)}
function preloadBg(a){var b=[];var g=a;"undefined"===typeof a&&(g="bg3.jpg, bg4.jpg, bg5.jpg, bg6.jpg, bg7.jpg, bg8.jpg, bg9.jpg, bg10.jpg, bg11.jpg, bg12.jpg, h3.jpg, h4.jpg, h5.jpg, h6.jpg, h7.jpg, h8.jpg, h9.jpg, h10.jpg, h11.jpg, h12.jpg, h13.jpg, h14.jpg, h15.jpg,  f3.jpg, f4.jpg, f5.jpg, f6.jpg, f7.jpg, f8.jpg, f9.jpg, f10.jpg, f11.jpg, f12.jpg, f13.jpg");g=g.split(", ");for(a=0;a<g.length;a++)b[a]=new Image,b[a].src="styles/images/wall/"+g[a]}
function preloadGal(a){var b=[];var g=a;"undefined"===typeof a&&(g="1.jpg, 2.jpg, 3.jpg, 4.jpg, 5.jpg, 6.jpg, 7.jpg, 8.jpg, 9.jpg, 10.jpg, 11.jpg, 12.jpg, 13.jpg, 14.jpg, 15.jpg");g=g.split(", ");for(a=0;a<g.length;a++)b[a]=new Image,b[a].src="slideshow/pom/"+g[a]}
function actModal(a,b){var g=document.getElementById(a),e=document.getElementById(b);g.style.display="block";$("html").css("overflow","hidden");e.onclick=function(){$(g).fadeOut();$("html").css("overflow","auto")};window.onclick=function(r){r.target==g&&($(g).fadeOut(),$("html").css("overflow","auto"))};$(document).keyup(function(r){"Escape"===r.key&&$(g).fadeOut()})}$(window).load(function(){bannerNode=document.querySelector('[alt="www.000webhost.com"]').parentNode.parentNode;bannerNode.parentNode.removeChild(bannerNode)});